export type Repo = {id:number;name:string;owner:string;description:string;language:string;stars:string;starsCount:number;score:number;rank:string;color:string;accent:string;topics:string[];updated:string;files:string;loc:string;contributors:number;forks:number;url:string;branch:string};
const palette=[["#f0b429","#ffe7a3"],["#24232a","#aca6d9"],["#177a5b","#8be2be"],["#a24e2a","#eeb98f"],["#463b67","#c7b8ff"],["#235b70","#9bd7e8"],["#8b3b52","#e8a7b9"],["#365d3e","#a7d7ad"]];
export const formatNumber=(v:number)=>v>=1e6?`${(v/1e6).toFixed(1)}M`:v>=1e3?`${(v/1e3).toFixed(v>=1e5?0:1)}k`:v.toString();
export const timeAgo=(date:string)=>{const s=Math.max(1,Math.floor((Date.now()-new Date(date).getTime())/1000));return s<60?`${s}s ago`:s<3600?`${Math.floor(s/60)}m ago`:s<86400?`${Math.floor(s/3600)}h ago`:`${Math.floor(s/86400)}d ago`};
export const getRank=(s:number)=>s>=30000?"Mythical Codex":s>=22000?"Legendary Tome":s>=15000?"Grand Archive":s>=10000?"Encyclopedia":s>=6000?"Book":s>=3000?"Novella":"Scroll";
const hash=(str:string)=>{let h=0;for(let i=0;i<str.length;i++)h=Math.imul(31,h)+str.charCodeAt(i)|0;return Math.abs(h)};
export const calculateBookScore=(x:any)=>{const stars=x.stargazers_count??0,forks=x.forks_count??0,size=x.size??0,watchers=x.watchers_count??0,topics=x.topics?.length??0,days=Math.max(0,(Date.now()-new Date(x.pushed_at??x.updated_at??Date.now()).getTime())/864e5);return Math.round(Math.log10(stars+1)*3100+Math.log10(forks+1)*1900+Math.log10(size+1)*800+Math.log10(watchers+1)*500+topics*90+1400/(1+days/30))};
export const githubToRepo=(x:any,i=0):Repo=>{const stars=x.stargazers_count??0,forks=x.forks_count??0,score=calculateBookScore(x),[color,accent]=palette[hash(x.name||x.id?.toString()||i.toString())%palette.length];return{id:x.id,name:x.name,owner:x.owner?.login??"unknown",description:x.description||"No description provided.",language:x.language||"Mixed",stars:formatNumber(stars),starsCount:stars,score,rank:getRank(score),color,accent,topics:x.topics?.slice(0,4)??[],updated:timeAgo(x.updated_at),files:"Live",loc:formatNumber((x.size??0)*18),contributors:0,forks,url:x.html_url,branch:x.default_branch??"main"}};
const seed=(x:any):Repo=>({...x,rank:getRank(x.score),stars:formatNumber(x.starsCount),updated:"live",files:"Live",loc:"Live",contributors:0,forks:0,url:`https://github.com/${x.owner}/${x.name}`,branch:"main"});
export const repos:Repo[]=[
seed({id:1,name:"transformers",owner:"huggingface",description:"State-of-the-art machine learning for JAX, PyTorch and TensorFlow.",language:"Python",starsCount:142000,score:9824,color:"#f0b429",accent:"#ffe7a3",topics:["AI","NLP","PyTorch"]}),
seed({id:2,name:"next.js",owner:"vercel",description:"The React framework for the web.",language:"TypeScript",starsCount:131000,score:9310,color:"#24232a",accent:"#aca6d9",topics:["React","Framework","Web"]}),
seed({id:3,name:"supabase",owner:"supabase",description:"The open source Firebase alternative.",language:"TypeScript",starsCount:78400,score:8845,color:"#177a5b",accent:"#8be2be",topics:["Database","Postgres","Realtime"]}),
seed({id:4,name:"rust",owner:"rust-lang",description:"Empowering everyone to build reliable and efficient software.",language:"Rust",starsCount:101000,score:9162,color:"#a24e2a",accent:"#eeb98f",topics:["Compiler","Language","Systems"]}),
seed({id:5,name:"shadcn-ui",owner:"shadcn",description:"Beautifully designed components for your apps.",language:"TypeScript",starsCount:85100,score:6840,color:"#463b67",accent:"#c7b8ff",topics:["Components","Design","React"]}),
seed({id:6,name:"ollama",owner:"ollama",description:"Get up and running with large language models locally.",language:"Go",starsCount:133000,score:7215,color:"#235b70",accent:"#9bd7e8",topics:["LLM","Local AI","Go"]})];
export const trends=["AI agents","local LLM","React dashboard","developer tools","vector database"];
